name: Code Review - Rust
on:
  push: null
env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.16.14
  RUST_TOOLCHAIN: 1.69.0
  LOG_PROGRAM: 4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init
    - name: Set Rust version
      run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }} --component rustfmt
    - name: Run fmt
      run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Set Rust version
      run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }} --component clippy
    - name: Run clippy
      run: cargo clippy --workspace --exclude anchor-\* --exclude fixed --exclude checked_math --features
        enable-gpl -- --no-deps --deny=warnings --allow=clippy::style --allow=clippy::complexity --allow=clippy::manual-retain
        --allow=clippy::crate-in-macro-def --allow=clippy::result-large-err --allow=clippy::derive_partial_eq_without_eq
  idl:
    name: IDL Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Check
      run: yarn ts-node ts/client/scripts/idl-compare.ts main/mango_v4.json mango_v4.json
  sca:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Fail on critical vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: Cargo.lock
        ignore-unfixed: true
        hide-progress: true
        format: table
        severity: CRITICAL
        exit-code: '1'
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Set Rust version
      run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
    - name: Install Solana
      run: 'sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"

        solana --version

        echo "Generating keypair..."

        solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent

        '
    - name: Build all deps
      run: 'cargo build-sbf --features enable-gpl || true

        cargo +solana build-sbf --features enable-gpl

        '
    - name: Run sbf tests
      run: cargo +solana test-sbf --features enable-gpl 2> >(tee raw-test-sbf.log >&2)
    - name: Install deps
      run: 'sudo apt-get install ripgrep

        curl -Lo xsv.tar.gz "https://github.com/BurntSushi/xsv/releases/latest/download/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz"

        sudo tar xf xsv.tar.gz -C /usr/local/bin

        '
    - name: Setup date input
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    - name: Process raw log
      run: "rg -oNI \"(Instruction: |Program ${{ env.LOG_PROGRAM }} consumed).*$\" raw-test-sbf.log \\\
        \n  | rg -U 'Instruction:.*\\nProgram ${{ env.LOG_PROGRAM }}.*' \\\n  | awk 'NR % 2 == 1 { o=$0\
        \ ; next } { print o \" \" $0 }' \\\n  | sort | uniq -u | sort > cu-per-ix.log\n"
    - name: Clean up log
      run: "rg -N 'Instruction: (\\w+) .* consumed (\\d+) .*' cu-per-ix.log -r '${{ steps.date.outputs.today\
        \ }},$1,$2' \\\n  | uniq | xsv sort -s 2 -N -R \\\n  | sort -t ',' -k 2,3 -u \\\n  | sort > cu-per-ix-clean.log\n"
    - name: Save clean log
      uses: actions/upload-artifact@v3
      with:
        name: cu-per-ix-clean
        path: cu-per-ix-clean.log
